CLASS LHC_ZZCIR_CIT_DB1_22BM05000005 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitDb122bm050000050
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_DB1_22BM05000005 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
